export const dossier = {
  positioning: {
    eyebrow: 'Posicionamento institucional',
    title: 'Uma extensão operacional, não uma concorrente.',
    intro: 'A T&G não pretende competir com transportadoras, marketplaces ou operadores logísticos. Seu papel é criar a infraestrutura regional que reduz a dificuldade de entrada dessas empresas em Arapiraca.',
    bullets: ['Evitar a abertura imediata de uma nova unidade', 'Reduzir custo e tempo de implantação', 'Começar com recursos proporcionais à demanda', 'Conectar a operação a apoio e conhecimento locais'],
    practical: 'Em vez de alugar um imóvel, reformar, contratar equipe, instalar sistemas e testar a operação durante meses, uma empresa poderá utilizar a T&G como base modular e ampliar o uso conforme o volume real.',
  },
  receiving: {
    eyebrow: 'Operação', title: 'Recebimento organizado em um ponto conhecido.',
    intro: 'A T&G pode atuar como endereço operacional para concentrar a entrada de mercadorias e reduzir entregas dispersas e falhas de comunicação.',
    bullets: ['Mercadorias de transportadoras', 'Produtos de lojistas e distribuidores', 'Encomendas para rotas locais', 'Volumes em transferência', 'Cargas aguardando redistribuição'],
    practical: 'Uma carga regional chega ao hub, é identificada e direcionada à área adequada antes da separação por rota ou operador.',
  },
  inspection: {
    eyebrow: 'Operação', title: 'Conferência para reduzir divergências.',
    intro: 'O nível de controle poderá variar conforme o modelo de parceria e o procedimento definido pelo operador.',
    bullets: ['Contagem de volumes', 'Verificação visual', 'Identificação de remetente e destino', 'Separação por rota', 'Registro de entrada', 'Indicação de avarias aparentes'],
    practical: 'Os volumes são verificados na chegada e organizados por destino, permitindo identificar divergências antes da expedição.',
  },
  temporaryStorage: {
    eyebrow: 'Operação', title: 'Armazenagem operacional, não permanência prolongada.',
    intro: 'O foco inicial é apoiar mercadorias que aguardam coleta, consolidação, conferência, rota ou expedição.',
    bullets: ['Formação de rotas', 'Coleta por entregadores', 'Consolidação de vendedores', 'Transferência entre veículos', 'Operações sazonais'],
    practical: 'Produtos recebidos antes do veículo de transferência permanecem organizados somente durante o intervalo necessário à próxima etapa.',
  },
  crossDocking: {
    eyebrow: 'Operação', title: 'Um ponto de passagem estruturado.',
    intro: 'A mercadoria pode chegar, ser conferida, separada e redirecionada no mesmo dia ou em curto intervalo.',
    bullets: ['Última milha', 'Redistribuição regional', 'Consolidação de cargas', 'Transferência entre veículos', 'Formação de rotas', 'Picos promocionais'],
    practical: 'Uma transportadora envia volumes pela manhã; o hub separa por região e disponibiliza as rotas locais sem armazenagem prolongada.',
  },
  shipping: {
    eyebrow: 'Operação', title: 'A transição entre o hub e a próxima etapa.',
    intro: 'A T&G pretende ser um ponto de convergência, sem criar dependência exclusiva de uma única transportadora.',
    bullets: ['Separação por destino', 'Formação de lotes', 'Organização por operador', 'Retirada por entregadores', 'Retirada empresarial', 'Transferência regional'],
    practical: 'Depois da conferência, os volumes são agrupados conforme destino e encaminhados ao canal logístico disponível para a operação.',
  },
  mobility: {
    eyebrow: 'Capacidade operacional', title: 'Mobilidade elétrica integrada à última milha.',
    intro: 'A T&G pretende conectar estrutura, equipamentos e oportunidades para tornar rotas urbanas mais econômicas.',
    bullets: ['Pequenos volumes', 'Trajetos curtos e frequentes', 'Recarga no hub', 'Suporte e manutenção planejados', 'Menor dependência de combustível'],
    practical: 'Um entregador retira uma rota compacta no hub e utiliza um veículo elétrico adequado ao percurso urbano.',
  },
  carrierRisk: {
    eyebrow: 'Para transportadoras', title: 'Amplie sua cobertura com menor investimento inicial.',
    intro: 'Uma entrada modular permite testar o mercado, estruturar rotas e ampliar o volume antes de assumir todos os custos de uma unidade própria.',
    bullets: ['Ponto de apoio', 'Cross docking regional', 'Base de última milha', 'Projeto-piloto', 'Operação sazonal', 'Unidade operacional terceirizada'],
    practical: 'Parte dos custos fixos de entrada pode se tornar custo operacional proporcional ao espaço, recebimento e apoio efetivamente utilizados.',
  },
  partnershipModels: {
    eyebrow: 'Modelos de parceria', title: 'Uma estrutura que acompanha o estágio da operação.',
    groups: [
      ['Ponto de apoio', 'Referência física para recebimento, retirada e organização de rotas.'],
      ['Operação terceirizada', 'Atividades definidas conforme procedimentos do parceiro.'],
      ['Projeto-piloto', 'Teste de demanda antes da abertura de unidade própria.'],
      ['Operação sazonal', 'Capacidade adicional durante períodos de alto volume.'],
    ],
    practical: 'O desenho comercial deve refletir o nível de serviço, controle, espaço e período necessários em cada parceria.',
  },
  merchantFlow: {
    eyebrow: 'Para lojistas', title: 'Sua loja vende. A T&G organiza o caminho até o cliente.',
    intro: 'A operação planejada reúne preparação, armazenagem temporária e possibilidade de encaminhamento conforme parcerias e integrações disponíveis.',
    bullets: ['Vendas pontuais e diárias', 'Pequenos e-commerces', 'Lojas físicas com vendas on-line', 'Vendedores de marketplaces', 'Campanhas sazonais', 'Comerciantes sem expedição própria'],
    practical: 'O lojista entrega produtos em lote; a operação prepara, identifica e separa cada volume para o canal disponível, reduzindo deslocamentos.',
  },
  courierBase: {
    eyebrow: 'Para entregadores', title: 'Quem entrega também precisa de estrutura.',
    intro: 'O hub pretende criar uma base profissional para retirada, espera, orientação, devolução e relacionamento com empresas parceiras.',
    bullets: ['Retirada de mercadorias', 'Organização de rotas', 'Espera entre entregas', 'Devolução de volumes', 'Carregamento elétrico', 'Formação de equipes'],
    practical: 'O entregador inicia e encerra rotas em um ponto conhecido, reduzindo tempo improdutivo e deslocamentos desorganizados.',
  },
  electricProgram: {
    eyebrow: 'Visão em implantação', title: 'Programa de mobilidade elétrica.',
    intro: 'A proposta está em desenvolvimento e não representa disponibilidade integral imediata.',
    bullets: ['Venda ou assinatura', 'Financiamento', 'Locação com opção de compra', 'Manutenção e peças', 'Suporte', 'Carregamento', 'Acesso a rotas compatíveis'],
    practical: 'O equipamento deixa de ser uma compra isolada e passa a integrar um ecossistema de estrutura e suporte conforme o programa evoluir.',
  },
  electricMobility: {
    eyebrow: 'Mobilidade elétrica', title: 'T&G Delivery Edition: conceito em desenvolvimento.',
    intro: 'Uma configuração padronizada pode facilitar manutenção, treinamento e gestão de frota.',
    bullets: ['Motor para uso profissional', 'Bateria removível', 'Autonomia urbana', 'Freios e pneus reforçados', 'Bagageiro e caixa de carga', 'Iluminação e rastreamento', 'Peças padronizadas'],
    practical: 'A bicicleta é dimensionada para pequenos volumes e rotas curtas e frequentes, com recarga e suporte associados ao hub.',
  },
  energy: {
    eyebrow: 'Energia sustentável', title: 'Energia como parte do modelo operacional.',
    intro: 'A geração solar planejada poderá reduzir custos do galpão e criar capacidade para carregamento elétrico.',
    bullets: ['Iluminação e administração', 'Câmeras e segurança', 'Carregamento de bicicletas', 'Carregamento futuro de motos', 'Sistemas de baterias', 'Futuras estações de recarga'],
    practical: 'Mercadoria chega → conferência → organização → rota → carregamento do veículo → retirada → entrega regional.',
  },
  technology: {
    eyebrow: 'Tecnologia e dados', title: 'Transformar atividades físicas em informação útil.',
    intro: 'A camada de gestão planejada organiza movimentações e ajuda parceiros a avaliar desempenho e expansão.',
    bullets: ['Registro de recebimento', 'Controle de entrada e saída', 'Histórico de movimentação', 'Separação por operador e rota', 'Comunicação com entregadores', 'Relatórios e disponibilidade'],
    groups: [['Indicadores previstos', 'Volumes por dia, permanência, expedição, avarias, devoluções, produtividade, uso do espaço, energia e economia potencial.']],
    practical: 'Um painel operacional poderá indicar onde volumes permanecem por mais tempo e quais rotas concentram maior demanda.',
  },
  arapiraca: {
    eyebrow: 'Por que Arapiraca', title: 'Um endereço com função regional.',
    intro: 'O valor estratégico está na possibilidade de transformar a localização em infraestrutura compartilhada para o Agreste.',
    bullets: ['Acesso ao interior de Alagoas', 'Proximidade com polos comerciais', 'Conexão com rotas estaduais', 'Atendimento a municípios próximos', 'Formação de rotas', 'Menos deslocamentos originados em Maceió'],
    practical: 'Volumes destinados a diferentes municípios podem convergir em Arapiraca antes da formação das rotas regionais.',
  },
  transparency: {
    eyebrow: 'Infraestrutura e transparência', title: 'Uma operação real começa com um endereço real.',
    intro: 'A sede na Rua Manoel Martins Lemos, 580, Primavera, é a base inicial do hub. A página diferencia com clareza o que existe, o que está em implantação e a visão futura.',
    groups: [['Existente', 'Imóvel próprio, endereço operacional, espaço e base institucional.'], ['Em implantação', 'Áreas, equipamentos, segurança, tecnologia, carregamento e parcerias.'], ['Visão futura', 'Frota, oficina, solar ampliada, sistemas, recarga e expansão.']],
    practical: 'Cada nova capacidade deve ser comunicada como disponível somente após sua implantação e validação operacional.',
  },
  revenue: {
    eyebrow: 'Parceiros e investidores', title: 'Fontes potenciais de receita complementares.',
    groups: [['Serviços logísticos', 'Recebimento, conferência, cross docking, armazenagem e expedição.'], ['Serviços a lojistas', 'Preparação, etiquetagem, postagem e fulfillment planejado.'], ['Mobilidade', 'Venda, assinatura, locação, manutenção, peças e acessórios.'], ['Energia e tecnologia', 'Recarga, geração, gestão, rastreamento, relatórios e integração.'], ['Infraestrutura', 'Uso por operadores, projetos-piloto, sazonalidade e contratos empresariais.']],
    practical: 'A diversificação reduz a dependência de uma única atividade, mas cada frente depende de implantação, demanda e parcerias.',
  },
  growth: {
    eyebrow: 'Tese de desenvolvimento', title: 'Comece pequeno. Opere com estrutura. Cresça com segurança.',
    intro: 'As fases representam uma direção estratégica, não uma promessa garantida de execução ou retorno.',
    bullets: ['Estrutura mínima', 'Operação regional', 'Mobilidade elétrica', 'Energia e tecnologia', 'Replicação'],
    practical: 'A passagem entre fases deve ocorrer conforme validação operacional, demanda, disponibilidade de capital e formalização de parceiros.',
  },
  caseCarrier: { eyebrow: 'Cenário demonstrativo', title: 'Transportadora entrando em Arapiraca', intro: 'Uma transportadora ainda não possui volume suficiente para abrir filial. Ela utiliza a T&G como ponto de apoio, organiza rotas locais e testa a demanda antes de assumir custos permanentes.', practical: 'Cenário hipotético; o formato real depende de contrato, capacidade e procedimentos acordados.' },
  caseMerchant: { eyebrow: 'Cenário demonstrativo', title: 'Lojista de marketplace', intro: 'Um lojista perde tempo com embalagem, etiquetas e deslocamentos. Ele deixa produtos na T&G para organização e direcionamento ao canal disponível.', practical: 'Cenário hipotético; serviços e operadores dependem das integrações disponíveis.' },
  caseCourier: { eyebrow: 'Cenário demonstrativo', title: 'Entregador com bicicleta elétrica', intro: 'Um entregador quer ampliar a capacidade sem assumir imediatamente o custo de uma motocicleta. Um futuro programa poderá oferecer equipamento, suporte, carregamento e rotas compatíveis.', practical: 'Programa futuro, sujeito a implantação e condições comerciais.' },
  caseSeasonal: { eyebrow: 'Cenário demonstrativo', title: 'Operação sazonal', intro: 'Uma empresa precisa ampliar capacidade durante uma campanha. O hub poderá receber, organizar e expedir o volume adicional durante o período necessário.', practical: 'Cenário hipotético; a capacidade deve ser confirmada para cada período.' },
}
