const makePage = ({
  path,
  category,
  eyebrow,
  title,
  summary,
  items = [],
  steps = [],
  cta = 'Solicitar proposta',
  secondaryCta,
  formIntent,
  related = [],
  note,
  variant = 'flow',
  faq,
}) => ({
  path,
  category,
  eyebrow,
  title,
  summary,
  items,
  steps: steps.length ? steps : [
    'Você apresenta a necessidade e o contexto da operação.',
    'A T&G avalia requisitos, viabilidade e formato de atendimento.',
    'A proposta define escopo, responsabilidades e próximo passo.',
  ],
  cta,
  secondaryCta,
  formIntent: formIntent || eyebrow,
  related,
  note,
  variant,
  faq: faq || [
    ['Como começar?', 'Envie sua necessidade pelo formulário. A primeira conversa serve para entender contexto, prazo e viabilidade.'],
    ['A proposta é personalizada?', 'Sim. O escopo depende do local, volume, uso, infraestrutura existente e objetivo do projeto.'],
    ['Onde a T&G opera?', 'A base de atendimento está em Arapiraca. A disponibilidade para cada localidade é confirmada durante a análise.'],
  ],
})

const logisticsRelated = ['/logistica/armazenagem', '/logistica/distribuicao-urbana', '/tg-hub-arapiraca']
const mobilityRelated = ['/veiculos-eletricos/bicicletas-eletricas', '/veiculos-eletricos/manutencao', '/carregadores/carregadores-para-bicicletas']
const solarRelated = ['/energia-solar/simulacao', '/carregadores/integracao-com-energia-solar', '/energia-solar/armazenamento-de-energia']
const chargingRelated = ['/carregadores/avaliar-instalacao', '/energia-solar', '/carregadores/carregadores-para-bicicletas']

export const routePages = {
  logistica: makePage({
    path: '/logistica',
    category: 'Logística',
    eyebrow: 'T&G Logística',
    title: 'Armazenagem, coleta e distribuição',
    summary: 'Apoio para empresas que precisam receber, organizar, armazenar e movimentar mercadorias com mais controle.',
    items: ['Recebimento de cargas', 'Armazenagem', 'Separação de pedidos', 'Ponto de coleta e retirada', 'Distribuição urbana', 'Apoio ao comércio eletrônico', 'Apoio a transportadoras', 'Organização de estoque', 'Preparação de pedidos'],
    steps: ['A empresa apresenta sua necessidade.', 'A T&G analisa volume, frequência e tipo de mercadoria.', 'A operação é dimensionada.', 'A proposta comercial é apresentada.', 'A operação é iniciada e acompanhada.'],
    cta: 'Solicitar operação logística',
    secondaryCta: 'Falar com atendimento',
    related: logisticsRelated,
    note: 'Capacidade, disponibilidade e valores são informados somente após a análise da operação.',
    variant: 'warehouse',
  }),
  'logistica/armazenagem': makePage({
    path: '/logistica/armazenagem', category: 'Logística', eyebrow: 'Armazenagem',
    title: 'Armazenagem em Arapiraca',
    summary: 'Estrutura para empresas que precisam manter mercadorias organizadas e disponíveis para retirada ou distribuição.',
    items: ['Recebimento', 'Conferência', 'Organização', 'Armazenagem', 'Controle de movimentação', 'Separação', 'Retirada', 'Expedição'],
    cta: 'Solicitar análise de armazenagem', related: logisticsRelated, variant: 'warehouse',
  }),
  'logistica/recebimento-de-cargas': makePage({
    path: '/logistica/recebimento-de-cargas', category: 'Logística', eyebrow: 'Recebimento de cargas',
    title: 'Recebimento de cargas',
    summary: 'Apoio local para o recebimento de mercadorias destinadas a empresas, lojas, transportadoras e operações de comércio eletrônico.',
    items: ['Agendamento', 'Recebimento', 'Conferência', 'Registro', 'Direcionamento', 'Armazenagem ou retirada'],
    cta: 'Consultar disponibilidade', related: logisticsRelated, variant: 'warehouse',
  }),
  'logistica/separacao-de-pedidos': makePage({
    path: '/logistica/separacao-de-pedidos', category: 'Logística', eyebrow: 'Preparação de pedidos',
    title: 'Separação e preparação de pedidos',
    summary: 'Organização de mercadorias para retirada, entrega local ou transferência para transportadoras.',
    items: ['Organização por pedido', 'Conferência', 'Preparação para retirada', 'Preparação para entrega local', 'Transferência para transportadoras'],
    cta: 'Apresentar volume de pedidos', related: logisticsRelated, variant: 'warehouse',
  }),
  'logistica/ponto-de-retirada': makePage({
    path: '/logistica/ponto-de-retirada', category: 'Logística', eyebrow: 'Ponto de retirada',
    title: 'Ponto de retirada em Arapiraca',
    summary: 'Estrutura para recebimento e retirada programada de mercadorias por clientes, parceiros, entregadores ou transportadoras.',
    items: ['Recebimento programado', 'Organização de volumes', 'Retirada por clientes', 'Atendimento a parceiros', 'Apoio a entregadores e transportadoras'],
    cta: 'Solicitar parceria', related: logisticsRelated, variant: 'warehouse',
  }),
  'logistica/distribuicao-urbana': makePage({
    path: '/logistica/distribuicao-urbana', category: 'Logística', eyebrow: 'Distribuição urbana',
    title: 'Distribuição urbana',
    summary: 'Apoio a operações de entrega e movimentação de mercadorias em Arapiraca e região.',
    items: ['Planejamento da necessidade', 'Organização das saídas', 'Integração com a base logística', 'Acompanhamento da operação'],
    cta: 'Consultar atendimento', related: logisticsRelated,
    note: 'A cobertura geográfica é confirmada conforme o tipo de operação e a disponibilidade.',
    variant: 'warehouse',
  }),
  'logistica/apoio-ao-ecommerce': makePage({
    path: '/logistica/apoio-ao-ecommerce', category: 'Logística', eyebrow: 'Apoio ao e-commerce',
    title: 'Apoio logístico para comércio eletrônico',
    summary: 'Recebimento, organização, preparação e retirada de pedidos para lojas que vendem pela internet.',
    items: ['Recebimento de mercadorias', 'Organização de estoque', 'Separação de pedidos', 'Ponto de retirada', 'Distribuição local', 'Integração com transportadoras'],
    cta: 'Apresentar minha operação', related: ['/solucoes/para-ecommerce', ...logisticsRelated], variant: 'warehouse',
  }),
  'logistica/apoio-a-transportadoras': makePage({
    path: '/logistica/apoio-a-transportadoras', category: 'Logística', eyebrow: 'Apoio a transportadoras',
    title: 'Base de apoio para transportadoras',
    summary: 'Estrutura regional para recebimento, transição, retirada e apoio a operações de distribuição.',
    items: ['Recebimento programado', 'Ponto de transição', 'Organização por rota', 'Retirada', 'Apoio sazonal', 'Projetos-piloto'],
    cta: 'Apresentar operação regional', related: ['/solucoes/para-transportadoras', '/parcerias/transportadoras', ...logisticsRelated], variant: 'warehouse',
  }),
  'logistica/solicitar-operacao': makePage({
    path: '/logistica/solicitar-operacao', category: 'Logística', eyebrow: 'Nova operação',
    title: 'Apresente sua operação logística',
    summary: 'Informe volume, frequência, tipo de mercadoria e prazo para que a T&G avalie o formato de atendimento.',
    items: ['Necessidade operacional', 'Volume estimado', 'Frequência', 'Tipo de mercadoria', 'Prazo para iniciar', 'Local de origem e destino'],
    cta: 'Enviar dados da operação', related: logisticsRelated, variant: 'conversion',
  }),

  'veiculos-eletricos': makePage({
    path: '/veiculos-eletricos', category: 'Veículos elétricos', eyebrow: 'T&G Mobilidade',
    title: 'Veículos elétricos para trabalho',
    summary: 'Soluções para entregadores, comércios, condomínios e empresas que buscam reduzir despesas de deslocamento e operação.',
    items: ['Bicicletas elétricas', 'Bicicletas de carga', 'Modelos para entregadores', 'Veículos leves', 'Acessórios', 'Baterias', 'Peças', 'Manutenção', 'Propostas para frotas'],
    cta: 'Conhecer os modelos', secondaryCta: 'Solicitar cotação', related: mobilityRelated, variant: 'mobility',
  }),
  'veiculos-eletricos/bicicletas-eletricas': makePage({
    path: '/veiculos-eletricos/bicicletas-eletricas', category: 'Veículos elétricos', eyebrow: 'Bicicletas elétricas',
    title: 'Bicicletas elétricas para deslocamento e trabalho',
    summary: 'Modelos para uso diário, entregas, deslocamento profissional e transporte de pequenas cargas.',
    items: ['Potência e autonomia sob consulta', 'Capacidade de carga', 'Tempo de recarga', 'Bateria removível ou fixa', 'Motor, pneus e freios', 'Transmissão', 'Garantia e prazo de entrega', 'Preço e condições de pagamento'],
    cta: 'Solicitar cotação', secondaryCta: 'Cadastrar interesse', related: mobilityRelated,
    note: 'Modelos, especificações, preços e disponibilidade serão publicados após confirmação dos fornecedores.',
    variant: 'mobility',
  }),
  'veiculos-eletricos/bicicletas-de-carga': makePage({
    path: '/veiculos-eletricos/bicicletas-de-carga', category: 'Veículos elétricos', eyebrow: 'Bicicletas de carga',
    title: 'Bicicletas elétricas de carga',
    summary: 'Modelos desenvolvidos para entregas, transporte de pequenas cargas e operações profissionais.',
    items: ['Entregas', 'Restaurantes', 'Lojas', 'Pequenos distribuidores', 'Condomínios', 'Equipes de manutenção', 'Operações internas', 'Frotas empresariais'],
    cta: 'Solicitar proposta', related: mobilityRelated, variant: 'mobility',
  }),
  'veiculos-eletricos/veiculos-para-entregadores': makePage({
    path: '/veiculos-eletricos/veiculos-para-entregadores', category: 'Veículos elétricos', eyebrow: 'Para entregadores',
    title: 'Mobilidade para entregadores',
    summary: 'Bicicletas elétricas, acessórios, baterias e suporte para quem utiliza o veículo como ferramenta de trabalho.',
    items: ['Modelos disponíveis', 'Capacidade de carga', 'Acessórios', 'Baús e suportes', 'Baterias', 'Manutenção', 'Condições de pagamento', 'Cadastro de interesse'],
    cta: 'Cadastrar interesse', related: ['/solucoes/para-entregadores', ...mobilityRelated], variant: 'mobility',
  }),
  'veiculos-eletricos/frotas-empresariais': makePage({
    path: '/veiculos-eletricos/frotas-empresariais', category: 'Veículos elétricos', eyebrow: 'Frotas empresariais',
    title: 'Frotas elétricas para empresas',
    summary: 'Propostas para empresas que desejam utilizar bicicletas ou veículos leves em entregas, deslocamentos internos ou atendimento de campo.',
    items: ['Análise de uso', 'Escolha do veículo', 'Quantidade necessária', 'Acessórios', 'Carregamento', 'Manutenção', 'Reposição de peças', 'Treinamento', 'Suporte'],
    cta: 'Solicitar proposta para frota', related: ['/carregadores/carregadores-para-empresas', ...mobilityRelated], variant: 'mobility',
  }),
  'veiculos-eletricos/baterias': makePage({
    path: '/veiculos-eletricos/baterias', category: 'Veículos elétricos', eyebrow: 'Baterias',
    title: 'Baterias para mobilidade elétrica',
    summary: 'Orientação, disponibilidade e suporte para baterias compatíveis com os modelos atendidos pela T&G.',
    items: ['Compatibilidade', 'Capacidade', 'Recarga', 'Cuidados de uso', 'Substituição', 'Disponibilidade sob consulta'],
    cta: 'Consultar bateria compatível', related: mobilityRelated, variant: 'mobility',
  }),
  'veiculos-eletricos/acessorios': makePage({
    path: '/veiculos-eletricos/acessorios', category: 'Veículos elétricos', eyebrow: 'Acessórios',
    title: 'Acessórios para bicicletas elétricas',
    summary: 'Soluções para adaptar o veículo ao uso diário, profissional e de entregas.',
    items: ['Baús', 'Suportes', 'Itens de carga', 'Iluminação', 'Segurança', 'Instalação sob consulta'],
    cta: 'Consultar acessórios', related: mobilityRelated, variant: 'mobility',
  }),
  'veiculos-eletricos/pecas': makePage({
    path: '/veiculos-eletricos/pecas', category: 'Veículos elétricos', eyebrow: 'Peças',
    title: 'Peças para bicicletas elétricas',
    summary: 'Consulta de peças de reposição conforme modelo, compatibilidade e disponibilidade.',
    items: ['Identificação do modelo', 'Análise de compatibilidade', 'Peças elétricas', 'Peças mecânicas', 'Prazo sob consulta'],
    cta: 'Solicitar peça', related: mobilityRelated, variant: 'mobility',
  }),
  'veiculos-eletricos/manutencao': makePage({
    path: '/veiculos-eletricos/manutencao', category: 'Veículos elétricos', eyebrow: 'Manutenção',
    title: 'Manutenção para bicicletas elétricas',
    summary: 'Avaliação e suporte progressivo para componentes mecânicos e elétricos dos modelos atendidos.',
    items: ['Diagnóstico inicial', 'Freios e transmissão', 'Sistema elétrico', 'Bateria', 'Ajustes', 'Peças sob consulta'],
    cta: 'Solicitar avaliação', related: mobilityRelated, variant: 'mobility',
    note: 'O atendimento depende do modelo, da peça e da capacidade técnica disponível.',
  }),
  'veiculos-eletricos/solicitar-cotacao': makePage({
    path: '/veiculos-eletricos/solicitar-cotacao', category: 'Veículos elétricos', eyebrow: 'Cotação',
    title: 'Solicite uma cotação de mobilidade elétrica',
    summary: 'Informe o uso pretendido, quantidade e necessidade de carga para receber orientação sobre os próximos passos.',
    items: ['Uso pessoal ou profissional', 'Quantidade', 'Carga transportada', 'Distância de uso', 'Acessórios', 'Manutenção e suporte'],
    cta: 'Enviar pedido de cotação', related: mobilityRelated, variant: 'conversion',
  }),

  'energia-solar': makePage({
    path: '/energia-solar', category: 'Energia solar', eyebrow: 'T&G Energia',
    title: 'Energia solar para reduzir despesas operacionais',
    summary: 'A T&G dimensiona sistemas solares para empresas, condomínios, imóveis rurais e residências.',
    items: ['Análise de consumo', 'Dimensionamento', 'Fornecimento de equipamentos', 'Instalação', 'Acompanhamento da geração', 'Manutenção', 'Sistemas híbridos', 'Armazenamento de energia', 'Integração com carregadores'],
    cta: 'Solicitar simulação', secondaryCta: 'Enviar conta de energia', related: solarRelated, variant: 'solar',
  }),
  'energia-solar/energia-solar-para-empresas': makePage({
    path: '/energia-solar/energia-solar-para-empresas', category: 'Energia solar', eyebrow: 'Energia para empresas',
    title: 'Energia solar para empresas',
    summary: 'Projetos dimensionados conforme o consumo, a estrutura do imóvel e os objetivos operacionais da empresa.',
    items: ['Análise de conta', 'Levantamento técnico', 'Dimensionamento', 'Fornecimento', 'Instalação', 'Monitoramento', 'Manutenção'],
    cta: 'Solicitar proposta empresarial', related: solarRelated, variant: 'solar',
  }),
  'energia-solar/energia-solar-para-condominios': makePage({
    path: '/energia-solar/energia-solar-para-condominios', category: 'Energia solar', eyebrow: 'Energia para condomínios',
    title: 'Energia solar para condomínios',
    summary: 'Projetos voltados ao consumo e à infraestrutura compartilhada do condomínio.',
    items: ['Áreas comuns', 'Iluminação', 'Elevadores', 'Bombas', 'Portarias', 'Carregadores', 'Infraestrutura compartilhada'],
    cta: 'Solicitar avaliação', related: ['/solucoes/para-condominios', ...solarRelated], variant: 'solar',
  }),
  'energia-solar/energia-solar-residencial': makePage({
    path: '/energia-solar/energia-solar-residencial', category: 'Energia solar', eyebrow: 'Energia residencial',
    title: 'Energia solar residencial',
    summary: 'Projeto dimensionado a partir do consumo, da estrutura do imóvel e das condições técnicas do local.',
    items: ['Análise da conta', 'Avaliação do imóvel', 'Dimensionamento', 'Equipamentos', 'Instalação', 'Monitoramento'],
    cta: 'Solicitar simulação residencial', related: solarRelated, variant: 'solar',
  }),
  'energia-solar/energia-solar-rural': makePage({
    path: '/energia-solar/energia-solar-rural', category: 'Energia solar', eyebrow: 'Energia rural',
    title: 'Energia solar para imóveis e atividades rurais',
    summary: 'Projetos avaliados conforme consumo, aplicação, estrutura disponível e estabilidade da rede.',
    items: ['Residências rurais', 'Bombas', 'Irrigação', 'Galpões', 'Armazenamento', 'Equipamentos', 'Sistemas híbridos', 'Locais com rede instável'],
    cta: 'Solicitar estudo', related: solarRelated,
    note: 'Autonomia e desempenho dependem de análise técnica; não são presumidos antes do dimensionamento.',
    variant: 'solar',
  }),
  'energia-solar/sistemas-hibridos': makePage({
    path: '/energia-solar/sistemas-hibridos', category: 'Energia solar', eyebrow: 'Sistemas híbridos',
    title: 'Sistemas híbridos de energia',
    summary: 'Integração entre geração solar, rede elétrica e armazenamento conforme a necessidade do projeto.',
    items: ['Análise de consumo', 'Perfil de uso', 'Geração solar', 'Armazenamento', 'Gestão das fontes', 'Projeto sob medida'],
    cta: 'Solicitar estudo técnico', related: solarRelated, variant: 'solar',
  }),
  'energia-solar/armazenamento-de-energia': makePage({
    path: '/energia-solar/armazenamento-de-energia', category: 'Energia solar', eyebrow: 'Armazenamento de energia',
    title: 'Armazenamento de energia',
    summary: 'Soluções com baterias avaliadas conforme carga, autonomia pretendida e condições da instalação.',
    items: ['Perfil de consumo', 'Cargas prioritárias', 'Capacidade necessária', 'Integração solar', 'Proteção e instalação', 'Monitoramento'],
    cta: 'Avaliar armazenamento', related: solarRelated, variant: 'solar',
  }),
  'energia-solar/manutencao': makePage({
    path: '/energia-solar/manutencao', category: 'Energia solar', eyebrow: 'Manutenção solar',
    title: 'Manutenção de sistemas solares',
    summary: 'Avaliação, acompanhamento e manutenção conforme o sistema instalado e o escopo técnico necessário.',
    items: ['Inspeção inicial', 'Verificação de geração', 'Componentes', 'Conexões', 'Monitoramento', 'Plano de atendimento'],
    cta: 'Solicitar avaliação do sistema', related: solarRelated, variant: 'solar',
  }),
  'energia-solar/simulacao': makePage({
    path: '/energia-solar/simulacao', category: 'Energia solar', eyebrow: 'Simulação solar',
    title: 'Simule seu projeto solar',
    summary: 'Envie o valor médio da sua conta e receba uma análise inicial.',
    items: ['Valor médio da conta', 'Tipo de imóvel', 'Consumo médio, se conhecido', 'Concessionária', 'Cidade e estado', 'Interesse em financiamento', 'Envio da conta de energia'],
    cta: 'Solicitar análise', related: solarRelated,
    note: 'A análise inicial é uma estimativa. Proposta e desempenho dependem de dados confiáveis e levantamento técnico.',
    variant: 'conversion',
  }),

  carregadores: makePage({
    path: '/carregadores', category: 'Carregadores', eyebrow: 'T&G Recarga',
    title: 'Carregadores para veículos e bicicletas elétricas',
    summary: 'Instalação de pontos de recarga em empresas, condomínios, estacionamentos, restaurantes e estabelecimentos comerciais.',
    items: ['Análise técnica', 'Escolha do carregador', 'Fornecimento', 'Instalação', 'Sinalização', 'Manutenção', 'Integração com energia solar', 'Análise da infraestrutura elétrica'],
    cta: 'Solicitar avaliação', related: chargingRelated, variant: 'charging',
  }),
  'carregadores/carregadores-para-empresas': makePage({
    path: '/carregadores/carregadores-para-empresas', category: 'Carregadores', eyebrow: 'Recarga empresarial',
    title: 'Carregadores para empresas',
    summary: 'Infraestrutura de recarga para colaboradores, clientes, visitantes e frotas.',
    items: ['Análise do perfil de uso', 'Infraestrutura elétrica', 'Escolha do equipamento', 'Instalação', 'Sinalização', 'Possível integração solar'],
    cta: 'Avaliar instalação empresarial', related: chargingRelated, variant: 'charging',
  }),
  'carregadores/carregadores-para-condominios': makePage({
    path: '/carregadores/carregadores-para-condominios', category: 'Carregadores', eyebrow: 'Recarga em condomínios',
    title: 'Carregadores para condomínios',
    summary: 'Avaliação técnica para pontos individuais ou compartilhados em condomínios.',
    items: ['Demanda dos moradores', 'Capacidade elétrica', 'Regras de uso', 'Medição', 'Instalação', 'Manutenção', 'Integração solar'],
    cta: 'Solicitar avaliação do condomínio', related: ['/solucoes/para-condominios', ...chargingRelated], variant: 'charging',
  }),
  'carregadores/carregadores-para-restaurantes': makePage({
    path: '/carregadores/carregadores-para-restaurantes', category: 'Carregadores', eyebrow: 'Recarga em restaurantes',
    title: 'Carregadores para restaurantes',
    summary: 'Ofereça recarga a clientes enquanto permanecem no estabelecimento.',
    items: ['Perfil de permanência', 'Área de estacionamento', 'Infraestrutura elétrica', 'Escolha do carregador', 'Sinalização', 'Integração solar'],
    cta: 'Avaliar local de instalação', related: ['/solucoes/para-restaurantes', ...chargingRelated], variant: 'charging',
  }),
  'carregadores/carregadores-para-hoteis': makePage({
    path: '/carregadores/carregadores-para-hoteis', category: 'Carregadores', eyebrow: 'Recarga em hotéis',
    title: 'Carregadores para hotéis',
    summary: 'Estrutura de recarga avaliada conforme permanência dos hóspedes, estacionamento e capacidade elétrica.',
    items: ['Perfil dos hóspedes', 'Vagas disponíveis', 'Infraestrutura elétrica', 'Controle de acesso', 'Sinalização', 'Integração solar'],
    cta: 'Avaliar instalação no hotel', related: ['/solucoes/para-hoteis', ...chargingRelated], variant: 'charging',
  }),
  'carregadores/carregadores-para-estacionamentos': makePage({
    path: '/carregadores/carregadores-para-estacionamentos', category: 'Carregadores', eyebrow: 'Recarga em estacionamentos',
    title: 'Carregadores para estacionamentos',
    summary: 'Pontos de recarga planejados conforme fluxo, permanência dos veículos e infraestrutura do local.',
    items: ['Fluxo de veículos', 'Tempo de permanência', 'Capacidade elétrica', 'Equipamentos', 'Sinalização', 'Operação e manutenção'],
    cta: 'Avaliar estacionamento', related: chargingRelated, variant: 'charging',
  }),
  'carregadores/carregadores-para-bicicletas': makePage({
    path: '/carregadores/carregadores-para-bicicletas', category: 'Carregadores', eyebrow: 'Recarga para bicicletas',
    title: 'Recarga para bicicletas elétricas',
    summary: 'Estrutura de recarga para empresas, condomínios, hubs, pontos de apoio e operações de entrega.',
    items: ['Pontos individuais', 'Pontos compartilhados', 'Armários para bateria', 'Carregamento controlado', 'Integração com energia solar', 'Sinalização', 'Suporte'],
    cta: 'Solicitar projeto', related: chargingRelated, variant: 'charging',
  }),
  'carregadores/integracao-com-energia-solar': makePage({
    path: '/carregadores/integracao-com-energia-solar', category: 'Carregadores', eyebrow: 'Recarga + energia solar',
    title: 'Integração de carregadores com energia solar',
    summary: 'Projeto coordenado entre geração solar, consumo do local e infraestrutura de recarga.',
    items: ['Perfil de consumo', 'Geração existente ou planejada', 'Demanda dos carregadores', 'Infraestrutura elétrica', 'Dimensionamento integrado', 'Monitoramento'],
    cta: 'Solicitar projeto integrado', related: chargingRelated, variant: 'charging',
  }),
  'carregadores/avaliar-instalacao': makePage({
    path: '/carregadores/avaliar-instalacao', category: 'Carregadores', eyebrow: 'Avaliação de instalação',
    title: 'Avalie a instalação de carregadores',
    summary: 'Informe o tipo de local, quantidade de vagas, uso pretendido e infraestrutura disponível.',
    items: ['Tipo de imóvel', 'Quantidade de pontos', 'Perfil de uso', 'Veículos atendidos', 'Infraestrutura elétrica', 'Integração solar'],
    cta: 'Solicitar avaliação técnica', related: chargingRelated, variant: 'conversion',
  }),

  solucoes: makePage({
    path: '/solucoes', category: 'Soluções', eyebrow: 'Soluções por perfil',
    title: 'Qual solução você procura?',
    summary: 'Escolha o perfil mais próximo da sua necessidade para encontrar serviços, aplicações e o próximo passo recomendado.',
    items: ['Empresas', 'Entregadores', 'Lojistas', 'Comércio eletrônico', 'Condomínios', 'Restaurantes', 'Hotéis', 'Transportadoras'],
    cta: 'Solicitar atendimento', related: ['/solucoes/para-empresas', '/solucoes/para-entregadores', '/solucoes/para-condominios'], variant: 'profile',
  }),
  'solucoes/para-empresas': makePage({
    path: '/solucoes/para-empresas', category: 'Soluções', eyebrow: 'Para empresas',
    title: 'Soluções para empresas',
    summary: 'Estrutura, mobilidade e energia organizadas conforme a necessidade operacional da empresa.',
    items: ['Redução de custos logísticos', 'Armazenagem', 'Operação de entregas', 'Implantação de frota elétrica', 'Energia solar', 'Carregadores para clientes e colaboradores'],
    cta: 'Solicitar proposta empresarial', related: ['/logistica', '/veiculos-eletricos/frotas-empresariais', '/energia-solar/energia-solar-para-empresas'], variant: 'profile',
  }),
  'solucoes/para-entregadores': makePage({
    path: '/solucoes/para-entregadores', category: 'Soluções', eyebrow: 'Para entregadores',
    title: 'Soluções para entregadores',
    summary: 'Mobilidade, acessórios e suporte para quem utiliza o veículo como ferramenta de trabalho.',
    items: ['Compra de bicicleta elétrica', 'Bicicletas de carga', 'Acessórios', 'Instalação de acessórios', 'Manutenção', 'Baterias', 'Apoio logístico', 'Oportunidades de parceria'],
    cta: 'Conhecer as bicicletas', secondaryCta: 'Cadastrar interesse', related: mobilityRelated, variant: 'profile',
  }),
  'solucoes/para-lojistas': makePage({
    path: '/solucoes/para-lojistas', category: 'Soluções', eyebrow: 'Para lojistas',
    title: 'Logística para lojas',
    summary: 'Apoio para receber, organizar, preparar e movimentar mercadorias em Arapiraca.',
    items: ['Recebimento', 'Armazenagem', 'Organização de estoque', 'Separação', 'Ponto de retirada', 'Distribuição local'],
    cta: 'Apresentar minha operação', related: logisticsRelated, variant: 'profile',
  }),
  'solucoes/para-ecommerce': makePage({
    path: '/solucoes/para-ecommerce', category: 'Soluções', eyebrow: 'Para e-commerce',
    title: 'Logística para comércio eletrônico',
    summary: 'Apoio a vendas online com recebimento, organização, preparação e retirada de pedidos.',
    items: ['Recebimento de mercadorias', 'Armazenagem', 'Organização de estoque', 'Separação de pedidos', 'Ponto de retirada', 'Distribuição local', 'Apoio a vendas online'],
    cta: 'Apresentar minha operação', related: logisticsRelated, variant: 'profile',
  }),
  'solucoes/para-condominios': makePage({
    path: '/solucoes/para-condominios', category: 'Soluções', eyebrow: 'Para condomínios',
    title: 'Soluções para condomínios',
    summary: 'Energia e recarga planejadas para a infraestrutura e o uso compartilhado do condomínio.',
    items: ['Instalação de carregadores', 'Energia solar', 'Pontos de recarga', 'Infraestrutura elétrica', 'Carregadores para bicicletas', 'Manutenção'],
    cta: 'Solicitar avaliação do condomínio', related: ['/energia-solar/energia-solar-para-condominios', '/carregadores/carregadores-para-condominios'], variant: 'profile',
  }),
  'solucoes/para-restaurantes': makePage({
    path: '/solucoes/para-restaurantes', category: 'Soluções', eyebrow: 'Para restaurantes',
    title: 'Soluções para restaurantes',
    summary: 'Logística, mobilidade e recarga avaliadas conforme a rotina do estabelecimento.',
    items: ['Apoio a recebimentos', 'Bicicletas de carga', 'Recarga para clientes', 'Energia solar', 'Infraestrutura elétrica'],
    cta: 'Solicitar avaliação', related: ['/carregadores/carregadores-para-restaurantes', '/veiculos-eletricos/bicicletas-de-carga'], variant: 'profile',
  }),
  'solucoes/para-hoteis': makePage({
    path: '/solucoes/para-hoteis', category: 'Soluções', eyebrow: 'Para hotéis',
    title: 'Soluções para hotéis',
    summary: 'Energia e infraestrutura de recarga planejadas para hóspedes, equipe e operação.',
    items: ['Carregadores para hóspedes', 'Energia solar', 'Infraestrutura elétrica', 'Sinalização', 'Manutenção'],
    cta: 'Solicitar avaliação', related: ['/carregadores/carregadores-para-hoteis', '/energia-solar'], variant: 'profile',
  }),
  'solucoes/para-transportadoras': makePage({
    path: '/solucoes/para-transportadoras', category: 'Soluções', eyebrow: 'Para transportadoras',
    title: 'Apoio regional para transportadoras',
    summary: 'Base em Arapiraca para apoiar recebimentos, transições e projetos operacionais.',
    items: ['Recebimento', 'Ponto de transição', 'Armazenagem temporária', 'Organização por rota', 'Retirada', 'Parcerias regionais'],
    cta: 'Apresentar operação', related: ['/logistica/apoio-a-transportadoras', '/parcerias/transportadoras'], variant: 'profile',
  }),

  'tg-hub-arapiraca': makePage({
    path: '/tg-hub-arapiraca', category: 'T&G Hub', eyebrow: 'T&G Hub Arapiraca',
    title: 'T&G Hub Arapiraca',
    summary: 'Estrutura dedicada ao apoio de operações logísticas, armazenagem, mobilidade elétrica e atendimento empresarial.',
    items: ['Recebimento e armazenamento', 'Organização de estoque', 'Retirada de mercadorias', 'Preparação de pedidos', 'Apoio a transportadoras', 'Exposição de veículos elétricos', 'Assistência e manutenção', 'Carregamento de baterias', 'Atendimento de parceiros'],
    cta: 'Apresentar minha operação', related: ['/logistica', '/parcerias', '/tg-hub-arapiraca/estrutura'],
    note: 'Sua empresa precisa de apoio logístico em Arapiraca? A T&G oferece estrutura para recebimento, armazenagem, retirada e distribuição de mercadorias.',
    variant: 'hub',
  }),
  'tg-hub-arapiraca/estrutura': makePage({
    path: '/tg-hub-arapiraca/estrutura', category: 'T&G Hub', eyebrow: 'Estrutura',
    title: 'Estrutura para apoiar operações em Arapiraca',
    summary: 'Base física para atendimento, recebimento, organização, demonstração e desenvolvimento de parcerias.',
    items: ['Área operacional', 'Atendimento empresarial', 'Recebimento', 'Organização', 'Showroom em implantação', 'Projetos dedicados'],
    cta: 'Conhecer a estrutura', related: ['/tg-hub-arapiraca', '/empresa/localizacao'], variant: 'hub',
  }),
  'tg-hub-arapiraca/armazenagem': makePage({
    path: '/tg-hub-arapiraca/armazenagem', category: 'T&G Hub', eyebrow: 'Armazenagem no Hub',
    title: 'Armazenagem no T&G Hub',
    summary: 'Apoio para mercadorias que precisam permanecer organizadas para retirada ou distribuição.',
    items: ['Recebimento', 'Conferência', 'Organização', 'Movimentação', 'Separação', 'Retirada'],
    cta: 'Solicitar análise', related: ['/logistica/armazenagem', '/tg-hub-arapiraca'], variant: 'hub',
  }),
  'tg-hub-arapiraca/ponto-de-retirada': makePage({
    path: '/tg-hub-arapiraca/ponto-de-retirada', category: 'T&G Hub', eyebrow: 'Retirada no Hub',
    title: 'Ponto de retirada no T&G Hub',
    summary: 'Retirada programada para clientes, parceiros, entregadores e transportadoras.',
    items: ['Programação', 'Identificação', 'Organização', 'Retirada', 'Atendimento a parceiros'],
    cta: 'Solicitar parceria', related: ['/logistica/ponto-de-retirada', '/tg-hub-arapiraca'], variant: 'hub',
  }),
  'tg-hub-arapiraca/apoio-logistico': makePage({
    path: '/tg-hub-arapiraca/apoio-logistico', category: 'T&G Hub', eyebrow: 'Apoio logístico',
    title: 'Apoio logístico em Arapiraca',
    summary: 'Uma base regional para empresas que precisam iniciar, testar ou apoiar uma operação.',
    items: ['Recebimento', 'Transição', 'Preparação', 'Retirada', 'Distribuição sob análise', 'Projetos-piloto'],
    cta: 'Apresentar operação', related: ['/logistica', '/tg-hub-arapiraca'], variant: 'hub',
  }),
  'tg-hub-arapiraca/showroom': makePage({
    path: '/tg-hub-arapiraca/showroom', category: 'T&G Hub', eyebrow: 'Showroom',
    title: 'Showroom de mobilidade e energia',
    summary: 'Área preparada para demonstração de soluções conforme disponibilidade de equipamentos e parceiros.',
    items: ['Bicicletas elétricas', 'Acessórios', 'Carregadores', 'Tecnologias de energia', 'Atendimento com agendamento'],
    cta: 'Cadastrar interesse em visita', related: ['/veiculos-eletricos', '/carregadores'], variant: 'hub',
    note: 'Produtos e demonstrações dependem da disponibilidade confirmada.',
  }),
  'tg-hub-arapiraca/manutencao': makePage({
    path: '/tg-hub-arapiraca/manutencao', category: 'T&G Hub', eyebrow: 'Manutenção no Hub',
    title: 'Apoio de manutenção no T&G Hub',
    summary: 'Capacidade progressiva para avaliação de bicicletas elétricas, acessórios e componentes atendidos.',
    items: ['Triagem', 'Diagnóstico', 'Ajustes', 'Peças sob consulta', 'Orientação', 'Encaminhamento técnico'],
    cta: 'Solicitar avaliação', related: ['/veiculos-eletricos/manutencao', '/tg-hub-arapiraca'], variant: 'hub',
  }),
  'tg-hub-arapiraca/apresentar-operacao': makePage({
    path: '/tg-hub-arapiraca/apresentar-operacao', category: 'T&G Hub', eyebrow: 'Apresente sua operação',
    title: 'Sua operação pode começar pelo T&G Hub',
    summary: 'Conte o que precisa receber, armazenar, preparar, retirar ou distribuir em Arapiraca.',
    items: ['Tipo de operação', 'Volume', 'Frequência', 'Mercadorias', 'Prazo', 'Necessidade de atendimento'],
    cta: 'Enviar operação para análise', related: ['/tg-hub-arapiraca', '/logistica/solicitar-operacao'], variant: 'conversion',
  }),

  parcerias: makePage({
    path: '/parcerias', category: 'Parcerias', eyebrow: 'Parcerias T&G',
    title: 'Parcerias T&G',
    summary: 'A T&G busca parceiros para ampliar operações de logística, mobilidade elétrica, energia e atendimento regional.',
    items: ['Transportadoras', 'Lojistas', 'Entregadores', 'Instaladores', 'Fornecedores', 'Empresas de tecnologia', 'Condomínios', 'Restaurantes', 'Pontos comerciais'],
    cta: 'Quero ser parceiro', related: ['/parcerias/seja-parceiro', '/tg-hub-arapiraca', '/empresa/sobre'], variant: 'partnership',
  }),
  'parcerias/parceiros-logisticos': makePage({
    path: '/parcerias/parceiros-logisticos', category: 'Parcerias', eyebrow: 'Parceiros logísticos',
    title: 'Parcerias para operações logísticas',
    summary: 'Conexões regionais para ampliar capacidade, cobertura e formatos de atendimento.',
    items: ['Operadores', 'Distribuidores', 'Pontos de apoio', 'Prestadores especializados', 'Projetos-piloto'],
    cta: 'Apresentar parceria logística', related: ['/logistica', '/parcerias/seja-parceiro'], variant: 'partnership',
  }),
  'parcerias/lojistas': makePage({
    path: '/parcerias/lojistas', category: 'Parcerias', eyebrow: 'Lojistas parceiros',
    title: 'Parcerias com lojistas',
    summary: 'Oportunidades de cooperação em logística, mobilidade, energia e atendimento local.',
    items: ['Ponto de retirada', 'Apoio a vendas online', 'Exposição de soluções', 'Indicação comercial', 'Projetos conjuntos'],
    cta: 'Apresentar parceria', related: ['/solucoes/para-lojistas', '/parcerias/seja-parceiro'], variant: 'partnership',
  }),
  'parcerias/transportadoras': makePage({
    path: '/parcerias/transportadoras', category: 'Parcerias', eyebrow: 'Transportadoras',
    title: 'Parcerias com transportadoras',
    summary: 'Estrutura regional e cooperação para recebimento, transição e distribuição sob análise.',
    items: ['Base regional', 'Recebimento', 'Ponto de transição', 'Apoio sazonal', 'Projetos-piloto'],
    cta: 'Apresentar operação', related: ['/logistica/apoio-a-transportadoras', '/parcerias/seja-parceiro'], variant: 'partnership',
  }),
  'parcerias/entregadores': makePage({
    path: '/parcerias/entregadores', category: 'Parcerias', eyebrow: 'Entregadores',
    title: 'Parcerias com entregadores',
    summary: 'Cadastro de interesse para mobilidade, apoio logístico e futuras oportunidades operacionais.',
    items: ['Bicicletas elétricas', 'Acessórios', 'Manutenção', 'Ponto de apoio', 'Cadastro de interesse'],
    cta: 'Cadastrar interesse', related: ['/solucoes/para-entregadores', '/veiculos-eletricos/veiculos-para-entregadores'], variant: 'partnership',
  }),
  'parcerias/fornecedores': makePage({
    path: '/parcerias/fornecedores', category: 'Parcerias', eyebrow: 'Fornecedores',
    title: 'Forneça soluções para o ecossistema T&G',
    summary: 'Conexões com fabricantes, distribuidores, instaladores e especialistas alinhados às frentes da T&G.',
    items: ['Logística', 'Mobilidade elétrica', 'Peças e acessórios', 'Energia solar', 'Carregadores', 'Tecnologia'],
    cta: 'Apresentar empresa e portfólio', related: ['/parcerias/seja-parceiro', '/empresa/atuacao'], variant: 'partnership',
  }),
  'parcerias/seja-parceiro': makePage({
    path: '/parcerias/seja-parceiro', category: 'Parcerias', eyebrow: 'Seja parceiro',
    title: 'Construa uma parceria com a T&G',
    summary: 'Apresente sua empresa, capacidade, proposta e região de atuação.',
    items: ['Empresa ou profissional', 'Área de atuação', 'Capacidade oferecida', 'Região', 'Experiência', 'Proposta de cooperação'],
    cta: 'Enviar proposta de parceria', related: ['/parcerias', '/tg-hub-arapiraca'], variant: 'conversion',
  }),

  empresa: makePage({
    path: '/empresa', category: 'Empresa', eyebrow: 'T&G Innovations',
    title: 'Estrutura regional, soluções práticas',
    summary: 'Conheça a atuação, a estrutura, a localização e os canais de atendimento da T&G.',
    items: ['Sobre a T&G', 'Áreas de atuação', 'Estrutura em Arapiraca', 'Contato', 'Localização'],
    cta: 'Conhecer a T&G', related: ['/empresa/sobre', '/empresa/estrutura', '/empresa/contato'], variant: 'company',
  }),
  'empresa/sobre': makePage({
    path: '/empresa/sobre', category: 'Empresa', eyebrow: 'Sobre a T&G',
    title: 'Sobre a T&G',
    summary: 'A T&G atua com soluções de logística, mobilidade elétrica e energia. A empresa atende negócios que precisam reduzir custos de transporte, organizar mercadorias, eletrificar operações ou gerar a própria energia.',
    items: ['Logística', 'Mobilidade elétrica', 'Energia solar', 'Infraestrutura de recarga', 'Atendimento empresarial', 'Desenvolvimento de parcerias'],
    cta: 'Conhecer as soluções', secondaryCta: 'Falar com a T&G', related: ['/empresa/atuacao', '/empresa/estrutura', '/empresa/contato'],
    note: 'Sua estrutura em Arapiraca funciona como base para atendimento, armazenagem, distribuição, demonstração de equipamentos e desenvolvimento de parcerias.',
    variant: 'company',
  }),
  'empresa/atuacao': makePage({
    path: '/empresa/atuacao', category: 'Empresa', eyebrow: 'Atuação',
    title: 'Infraestrutura, mobilidade e energia conectadas',
    summary: 'A T&G organiza soluções práticas para necessidades operacionais de empresas, profissionais e empreendimentos.',
    items: ['Logística regional', 'Veículos elétricos', 'Energia solar', 'Carregadores', 'Hub em Arapiraca', 'Parcerias'],
    cta: 'Conhecer as soluções', related: ['/logistica', '/veiculos-eletricos', '/energia-solar'], variant: 'company',
  }),
  'empresa/estrutura': makePage({
    path: '/empresa/estrutura', category: 'Empresa', eyebrow: 'Estrutura',
    title: 'Uma base regional para desenvolver soluções reais',
    summary: 'A estrutura da T&G em Arapiraca apoia atendimento, operações compatíveis, demonstrações e parcerias.',
    items: ['Base física', 'Atendimento', 'Apoio logístico', 'Showroom em implantação', 'Manutenção progressiva', 'Conexão de parceiros'],
    cta: 'Conhecer o T&G Hub', related: ['/tg-hub-arapiraca', '/empresa/localizacao'], variant: 'company',
  }),
  'empresa/contato': makePage({
    path: '/empresa/contato', category: 'Empresa', eyebrow: 'Contato',
    title: 'Fale com a T&G',
    summary: 'Informe sua necessidade para que a conversa seja direcionada à solução adequada.',
    items: ['Serviço logístico', 'Mobilidade elétrica', 'Energia solar', 'Carregadores', 'Manutenção', 'Parcerias'],
    cta: 'Solicitar atendimento', related: ['/solicitar-proposta', '/empresa/localizacao'], variant: 'conversion',
  }),
  'empresa/localizacao': makePage({
    path: '/empresa/localizacao', category: 'Empresa', eyebrow: 'Localização',
    title: 'T&G em Arapiraca',
    summary: 'Rua Manoel Martins Lemos, 580, Primavera, Arapiraca, Alagoas.',
    items: ['Atendimento com agendamento', 'Base regional', 'Apoio a operações', 'Desenvolvimento de parcerias'],
    cta: 'Solicitar atendimento', related: ['/tg-hub-arapiraca', '/empresa/contato'], variant: 'company',
  }),
  'solicitar-proposta': makePage({
    path: '/solicitar-proposta', category: 'Atendimento', eyebrow: 'Solicitar proposta',
    title: 'Qual solução sua empresa precisa?',
    summary: 'Informe sua necessidade e a equipe da T&G entrará em contato.',
    items: ['Serviço logístico', 'Armazenagem', 'Bicicleta elétrica', 'Bicicleta de carga', 'Frota empresarial', 'Energia solar', 'Carregador', 'Manutenção', 'Parceria'],
    cta: 'Solicitar atendimento', related: ['/logistica/solicitar-operacao', '/veiculos-eletricos/solicitar-cotacao', '/energia-solar/simulacao'], variant: 'conversion',
  }),
}

// Rotas antigas continuam válidas e exibem o conteúdo equivalente.
export const routeAliases = {
  'e-bikes': 'veiculos-eletricos',
  galpao: 'tg-hub-arapiraca',
  sobre: 'empresa/sobre',
  contato: 'empresa/contato',
}

export const routePaths = [...Object.keys(routePages), ...Object.keys(routeAliases)]

export function getRoutePage(route) {
  const canonicalRoute = routeAliases[route] || route
  return { page: routePages[canonicalRoute], canonicalRoute }
}

export function routeLabel(path) {
  const key = path.replace(/^\/|\/$/g, '')
  return routePages[key]?.eyebrow || key.split('/').pop()?.replaceAll('-', ' ')
}
